name: Engine Comparison

on:
  workflow_dispatch:

jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt install -y curl binutils bc

      - name: Download engines
        run: |
          curl -sL https://raw.githubusercontent.com/suprateem-ux/BotLi/main/engines/Supranova11.0 -o supranova11.0
          curl -sL https://github.com/cosmobobak/viridithas/releases/download/v18.0.0/viridithas-linux -o viridithas
          chmod +x supranova11.0 viridithas

      - name: Extract UCI options
        run: |
          echo -e "uci\nquit" | ./supranova11.0 > uci_supra.txt || echo "Supranova11.0 failed"
          echo -e "uci\nquit" | ./viridithas > uci_viri.txt || echo "Viridithas failed"

      - name: Extract strings
        run: |
          strings -n 6 supranova11.0 | sort -u > strings_supra.txt || echo "Supranova11.0 strings failed"
          strings -n 6 viridithas | sort -u > strings_viri.txt || echo "Viridithas strings failed"

      - name: Compute similarities
        run: |
          # UCI similarity
          uci_total=$(cat uci_supra.txt uci_viri.txt | sort -u | wc -l)
          uci_common=$(comm -12 <(sort uci_supra.txt) <(sort uci_viri.txt) | wc -l)
          uci_percent=$(echo "scale=2; $uci_common/$uci_total*100" | bc)

          # Strings similarity
          total_supra=$(wc -l < strings_supra.txt)
          total_viri=$(wc -l < strings_viri.txt)
          common=$(comm -12 strings_supra.txt strings_viri.txt | wc -l)
          string_percent=$(echo "scale=2; $common/($total_supra+$total_viri-$common)*100" | bc)

          # Combine into final percentage
          final=$(echo "scale=2; ($uci_percent+$string_percent)/2" | bc)

          echo "===== ENGINE SIMILARITY REPORT ====="
          echo "UCI options similarity: $uci_percent%"
          echo "Strings similarity:     $string_percent%"
          echo "FINAL PROOF SCORE:      $final%"
          if (( $(echo "$final >= 80" | bc -l) )); then
            echo "Verdict: Supranova11.0 is highly likely Viridithas (rebrand/mod)"
          else
            echo "Verdict: Supranova11.0 is NOT Viridithas"
          fi
