name: UCI Options Similarity

on:
  workflow_dispatch:

jobs:
  compare_uci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt install -y curl bc

      - name: Download engines
        run: |
          curl -sL https://raw.githubusercontent.com/suprateem-ux/BotLi/main/engines/Supranova11.0 -o supranova11.0
          curl -sL https://github.com/cosmobobak/viridithas/releases/download/v18.0.0/viridithas-linux -o viridithas
          chmod +x supranova11.0 viridithas

      - name: Extract UCI options
        run: |
          echo -e "uci\nquit" | ./supranova11.0 > uci_supra.txt || echo "Supranova11.0 failed"
          echo -e "uci\nquit" | ./viridithas > uci_viri.txt || echo "Viridithas failed"

      - name: Compute UCI similarity
        run: |
          total_supra=$(wc -l < uci_supra.txt)
          total_viri=$(wc -l < uci_viri.txt)
          common=$(comm -12 <(sort uci_supra.txt) <(sort uci_viri.txt) | tee common_lines.txt | wc -l)
          percent=$(echo "scale=2; $common/($total_supra + $total_viri - $common)*100" | bc)
          
          echo "===== UCI OPTIONS SIMILARITY REPORT ====="
          echo "Total Supranova11.0 lines: $total_supra"
          echo "Total Viridithas lines:    $total_viri"
          echo "Common lines:              $common"
          echo "Similarity percentage:     $percent%"
          echo "----------------------------------------"
          if (( $(echo "$percent >= 80" | bc -l) )); then
            echo "Verdict: Engines are highly similar (possible rebrand/mod)"
          else
            echo "Verdict: Engines are NOT highly similar"
          fi
